### ISSUE TITLE
Add sqlite version

### ISSUE THREAD

**Issue by f-cramer** [ory/scoop-hydra#1]
For development purposes it would be greated if one would be able to install the sqlite version of hydra via scoop

**Comment by aeneasr** [comment]
As far as I understand, the version is the SQLite one? See https://github.com/ory/scoop-hydra/blob/master/hydra.json#L12

**Comment by f-cramer** [comment]
Oh yes, you are obviously correct. To be honest I did not check again after the update to 1.9.2, but with 1.9.1 the version without sqlite was used.

**Comment by aeneasr** [comment]
Yup, I don't remember fixing that but apparently that's the case :) Closing because resolved but feel free to comment if you encounter more issues around this.

**Comment by f-cramer** [comment]
The current version (2.10.1) does not ship with sqlite support. The "fluctuation" in sqlite support unfortunately makes it pretty hard to use this repository for development.

**Comment by aeneasr** [comment]
You can just download the binary from the github releases page.

**Comment by f-cramer** [comment]
Oh, I know that and did it already before posting.
I just thought that because this repository is mentioned as the main installation method in your [documentation](https://www.ory.sh/hydra/docs/install), it should serve a somewhat reliable "version" of hydra (either alwayswith or always without sqlite support, not some combination of both).
I guess its better to just fork my own repository, then I can be sure to always have the version I prefer in it :D
